### ISSUE TITLE
Licence for content

### ISSUE THREAD

**Issue by ncclementi** [IanHawke/NumericalMethods#2]
@IanHawke The material looks great I might use something of these for a future course. I noticed you have a MIT license that only covers code. You might want to add an extra license for the instructional material, something like a Creative Commons Attribution license. If you want an example, in the you can follow the License file in [numerical mooc](https://github.com/numerical-mooc/numerical-mooc/blob/master/LICENSE) repository.

**Comment by IanHawke** [comment]
You're right: changed in 7bc25d882f287a21e9646c676c95672414c980ff
